### ISSUE TITLE
Incompatibility with A1111 WebUI

### ISSUE THREAD

**Issue by D0n-A** [vladmandic/sd-extension-nudenet#6]
Hello! There is the following: although you do not claim backward compatibility with the official SD from AUTOMATIC1111, can you fix it so that it works there too. We tried different combinations of checkboxes and other settings, but the extension is simply silent and does not work.

I also even tried to put the following positions - the result is the same.
![01](https://github.com/vladmandic/sd-extension-nudenet/assets/38649081/f46b2d2f-b4b3-4553-aed3-a5125e7cfc6d)

There are no errors in the console, except that by turning the sliders to maximum and setting all the filters, the following is displayed:
```
████████████████████████████████████████████████████████████████████████████| 20/20 [00:37<00:00,  1.88s/it]
*** Error running postprocess_image: D:\AI\NS\extensions\sd-extension-nudenet\scripts\nudenet-ext.py<00:00,  1.85s/it]
    Traceback (most recent call last):
      File "D:\AI\NS\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\AI\NS\extensions\sd-extension-nudenet\scripts\nudenet-ext.py", line 58, in postprocess_image
        process(p, pp, enabled, metadata, copy, score, blocks, censor, method, overlay)
      File "D:\AI\NS\extensions\sd-extension-nudenet\scripts\nudenet-ext.py", line 35, in process
        info = processing.create_infotext(p)
    TypeError: create_infotext() missing 3 required positional arguments: 'all_prompts', 'all_seeds', and 'all_subseeds'
```
Version: v1.6.0-2-g4afaaf8a

I would like to be able to use it there too, as it is convenient, simple and fast.
Hope for your help, thank you.

**Comment by vladmandic** [comment]
making it compatible with a1111 should be relatively easy, but i dont have or plan to install a1111 to test.
however, contributions and/or PRs would be welcome.

**Comment by vladmandic** [comment]
extension for a1111 is done by w-e-w in https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor
